namespace Portal.Application.Common.Interfaces;

/// <summary>Binary storage for uploaded files. Keys are generated by the storage, never by the client.</summary>
public interface IFileStorage
{
    /// <summary>Stores the content and returns the key to read it back.</summary>
    Task<string> SaveAsync(Stream content, string extension, CancellationToken ct = default);

    /// <summary>Opens a stored file, or returns null if it no longer exists.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken ct = default);

    Task DeleteAsync(string key, CancellationToken ct = default);
}
